- name: Ensure the partition is mounted
  include_role:
    name: mounted_partition
  when: mounts | list | length | int == 0

- name: At this point, there must exist a mount point
  assert:
    that:
      - mounts | list | length | int > 0

- name: Set fact for the arch chroot mount path
  set_fact:
    arch_chroot_mount_path: "{{ mounts | first }}"